[env]
_.path = ["node_modules/.bin"]
POSTGRESQL_URL = "postgresql://postgres:postgres@localhost:5432/postgres?schema=public"
VALKEY_HOST: "localhost"


[tools]
node = "lts"
pnpm = "latest"

[tasks.check]
depends = ["prepare"]
run = "biome check --write --unsafe"

[tasks.prepare]
outputs = ["node_modules/.pnpm/lock.yaml"]
run = "pnpm install"
sources = ["pnpm-lock.yaml"]

[tasks.start]
sources = ["pnpm-lock.yaml", "src/**/*.ts"]
run = "tsx src"
